### PR TITLE
Upgrade to new hcaptcha URL address

### PR DESCRIPTION
**Pull request by jfcalvo**
I found a warning in the console about upgrading to the new JS hCaptcha URL.

### CODE REVIEW

**Comment by jfcalvo** [comment]
@sebastiangrebe please can you take a look?

Looks like some PRs has been waiting for years to be approved and merged. Thanks.

**Comment by jfcalvo** [comment]
@sebastiangrebe please can you take a look?

Looks like some PRs has been waiting for years to be approved and merged. Thanks.

**Comment by jfcalvo** [comment]
@sebastiangrebe please can you take a look?

Looks like some PRs has been waiting for years to be approved and merged. Thanks.

**Comment by sebastiangrebe** [comment]
@jfcalvo As you can assume this package is maintained in free time so I cannot keep this maybe as updated as you like!
Feel free to create PRs though and keep a better attitude next time.
Thank you for the PR!

**Comment by jfcalvo** [comment]
> @jfcalvo As you can assume this package is maintained in free time so I cannot keep this maybe as updated as you like!
> Feel free to create PRs though and keep a better attitude next time.
> Thank you for the PR!

I wasn't trying to be rude 😃. Sorry if I gave that impression and thanks for merging it.

**Comment by sebastiangrebe** [comment]
@jfcalvo No problem!
Can you check if it works for you, I would then release a new version of this package?

**Comment by jfcalvo** [comment]
Yes, it's working fine. Feel free to create that new release.

**Pull request merged**
